management:
  endpoints:
    web:
      base-path: /private
      path-mapping:
        prometheus: metrics
      exposure:
        include:
          - prometheus
          - info

info:
  app:
    name: MyService
    description: My Awesome Service
    version: 1.0.0